// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3FY07hI17hR_7KP84avpNE2-I1qtqhM',
    appId: '1:99863140088:web:cdd1ca56185d226b890d0d',
    messagingSenderId: '99863140088',
    projectId: 'term-project-87561',
    authDomain: 'term-project-87561.firebaseapp.com',
    storageBucket: 'term-project-87561.firebasestorage.app',
    measurementId: 'G-N9FQSL1P9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy40nGSpWrygL__72SuDqIymH3Ckc7m7A',
    appId: '1:99863140088:android:207b35879b0c62a9890d0d',
    messagingSenderId: '99863140088',
    projectId: 'term-project-87561',
    storageBucket: 'term-project-87561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbgW1zubxSPNKRfjx4UaU0EErXluBtXU',
    appId: '1:99863140088:ios:768d5131de986398890d0d',
    messagingSenderId: '99863140088',
    projectId: 'term-project-87561',
    storageBucket: 'term-project-87561.firebasestorage.app',
    iosClientId: '99863140088-t7m3j3lev8qo3dqt3muc5c380792bg85.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbgW1zubxSPNKRfjx4UaU0EErXluBtXU',
    appId: '1:99863140088:ios:768d5131de986398890d0d',
    messagingSenderId: '99863140088',
    projectId: 'term-project-87561',
    storageBucket: 'term-project-87561.firebasestorage.app',
    iosClientId: '99863140088-t7m3j3lev8qo3dqt3muc5c380792bg85.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw3FY07hI17hR_7KP84avpNE2-I1qtqhM',
    appId: '1:99863140088:web:44968aae0340c47b890d0d',
    messagingSenderId: '99863140088',
    projectId: 'term-project-87561',
    authDomain: 'term-project-87561.firebaseapp.com',
    storageBucket: 'term-project-87561.firebasestorage.app',
    measurementId: 'G-Y9SH7RSGP0',
  );

}